{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "df9f8110",
   "metadata": {},
   "source": [
    "# Numpy and Inbuilt Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "18a49a4f",
   "metadata": {},
   "source": [
    "**What are Arrays** : \n",
    "\n",
    "The Data Type which stores the values of same time. This is sthe difference between list and array List can have elements of different types unlike arrays"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "484aef68",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "525b63ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "#converting list to array\n",
    "\n",
    "my_list = [1,2,3,4]\n",
    "arr = np.array(my_list)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3760891d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'numpy.ndarray'>\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array([1, 2, 3, 4])"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "print(type(arr))\n",
    "arr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "443b0028",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4]\n"
     ]
    }
   ],
   "source": [
    "print(arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "054a657c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(4,)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#checking number of ROWS and COLUMNS\n",
    "arr.shape "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "326b9a79",
   "metadata": {},
   "outputs": [],
   "source": [
    "arr = arr.reshape(2,2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c14602d6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1, 2],\n",
       "       [3, 4]])"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "42373c37",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2, 2)"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "081c3896",
   "metadata": {},
   "outputs": [],
   "source": [
    "#creating 2D Array\n",
    "list1 = [1,2,3,4,5]\n",
    "list2 = [6,7,8,9,10]\n",
    "list3 = [11,12,13,14,15]\n",
    "\n",
    "arr1 = np.array([list1,list2,list3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "d807de4c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3,  4,  5],\n",
       "       [ 6,  7,  8,  9, 10],\n",
       "       [11, 12, 13, 14, 15]])"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "e9eec9e1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(3, 5)"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "b2882fae",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "15"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1.size #total number of elements in arr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "18229c51",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3],\n",
       "       [ 4,  5,  6],\n",
       "       [ 7,  8,  9],\n",
       "       [10, 11, 12],\n",
       "       [13, 14, 15]])"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1.reshape(5,3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "8d431d35",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1],\n",
       "       [ 2],\n",
       "       [ 3],\n",
       "       [ 4],\n",
       "       [ 5],\n",
       "       [ 6],\n",
       "       [ 7],\n",
       "       [ 8],\n",
       "       [ 9],\n",
       "       [10],\n",
       "       [11],\n",
       "       [12],\n",
       "       [13],\n",
       "       [14],\n",
       "       [15]])"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1.reshape(15,1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "116cb06f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1.reshape(1,15)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "097600e5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3,  4,  5],\n",
       "       [ 6,  7,  8,  9, 10],\n",
       "       [11, 12, 13, 14, 15]])"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Indexing in ndarray\n",
    "\n",
    "arr1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "ec34f4e2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 2, 3, 4, 5])"
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1[0] #0 is used to access first row"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "8494d4a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1[0,1] #Second element of first column"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "f9643feb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 1,  6, 11])"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1[:,0] #all rows for first Column"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "21fc23e2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3,  4,  5],\n",
       "       [ 6,  7,  8,  9, 10]])"
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1[0:2,:] #all the columns for rows between one and two"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "a6ee489e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 9, 10],\n",
       "       [14, 15]])"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Accessing the section of array\n",
    "arr1[1:,3:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "415129f5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 7,  8],\n",
       "       [12, 13]])"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1[1:,1:3]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ea9113be",
   "metadata": {},
   "source": [
    "**Some Inbuilt Functions**"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd632fc1",
   "metadata": {},
   "source": [
    "**Arange**\n",
    "\n",
    "*np.arange(start,stop(excluding),step)*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "8a8bccef",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr2 = np.arange(0,10)\n",
    "arr2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "18bed30d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,\n",
       "       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])"
      ]
     },
     "execution_count": 54,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr3 = np.arange(0,10,0.5)\n",
    "arr3"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c16b713d",
   "metadata": {},
   "source": [
    "**linspace**\n",
    "\n",
    "\n",
    "*np.linspace(start,end(including),#ofequal parts)*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "a57d6d3b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,\n",
       "        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,\n",
       "        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,\n",
       "        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])"
      ]
     },
     "execution_count": 55,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.linspace(0,10,20)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ff4fc2ed",
   "metadata": {},
   "source": [
    "**Copy and Broadcasting**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "4dc20621",
   "metadata": {},
   "outputs": [],
   "source": [
    "arr1[1:,3:] = 10"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "f1b449b9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1,  2,  3,  4,  5],\n",
       "       [ 6,  7,  8, 10, 10],\n",
       "       [11, 12, 13, 10, 10]])"
      ]
     },
     "execution_count": 58,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "c0a0e120",
   "metadata": {},
   "outputs": [],
   "source": [
    "arr2 = arr1.copy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "5daf775a",
   "metadata": {},
   "outputs": [],
   "source": [
    "arr2[2:,2:] =500"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "3de8dc88",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[  1,   2,   3,   4,   5],\n",
       "       [  6,   7,   8,  10,  10],\n",
       "       [ 11,  12, 500, 500, 500]])"
      ]
     },
     "execution_count": 66,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "675ccf2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#some useful Conditions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "id": "0ee28477",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[ True  True  True  True  True]\n",
      " [ True False False False False]\n",
      " [False False False False False]]\n",
      "[1 2 3 4 5 6]\n"
     ]
    }
   ],
   "source": [
    "val = 7\n",
    "\n",
    "print(arr1<val)\n",
    "\n",
    "print(arr1[arr1<val])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "add8d950",
   "metadata": {},
   "source": [
    "**Ones**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "a8ff3088",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1., 1., 1., 1., 1., 1., 1.])"
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.ones(7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "8b4ecdac",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 1, 1, 1, 1, 1, 1])"
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.ones(7,dtype=int)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "id": "8cf60b69",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1, 1],\n",
       "       [1, 1]])"
      ]
     },
     "execution_count": 85,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.ones([2,2],dtype=int)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3e7ead6b",
   "metadata": {},
   "source": [
    "**Rand**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "id": "a7dcadee",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0.74500637, 0.09705345, 0.84935188],\n",
       "       [0.61063721, 0.73042251, 0.90625487],\n",
       "       [0.29768565, 0.42333983, 0.17603279]])"
      ]
     },
     "execution_count": 99,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr_ex = np.random.rand(3,3)\n",
    "arr_ex"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "39fd6dcf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0.70591754,  0.24900629, -0.62011616],\n",
       "       [ 0.26246792,  0.03563693,  1.24889214],\n",
       "       [ 0.37334302, -0.38789768,  0.10315134]])"
      ]
     },
     "execution_count": 105,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "arr_ex1 = np.random.randn(3,3) #this functions selects values based on standard normal distributions\n",
    "arr_ex1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "0da6a25f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import seaborn as sns\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "id": "dd27502b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "F:\\DS\\anaconda3\\lib\\site-packages\\seaborn\\distributions.py:2557: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).\n",
      "  warnings.warn(msg, FutureWarning)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:ylabel='Density'>"
      ]
     },
     "execution_count": 107,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYgAAAD4CAYAAAD2FnFTAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAlwklEQVR4nO3deXxU5d338c8ve0JCWBK2QEjYF9nDpiCorVurlLrvIoi0are7i3ef+2Xt01V719a2KqVIFSxQq7bFFjdUFGXfZScsCZElC2EnkOV6/sjYJ02HZBJzcibJ9/16zSszc66Z+c2VSb5zzrnOdcw5h4iISHURfhcgIiLhSQEhIiJBKSBERCQoBYSIiASlgBARkaCi/C6grlJSUlxGRobfZYiINCnr1q0rdM6l1uUxTS4gMjIyWLt2rd9liIg0KWaWU9fHaBOTiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFAKCBERCUoBISIiQSkgREQkKAWEiIgE5dmR1GY2B/gikO+cu6iGdiOBlcAtzrmXvapHBGD+qlxPn//20emePr9IY/JyDeJ54OqaGphZJPA48KaHdYiISD14FhDOuQ+Ao7U0exh4Bcj3qg4REakf3/ZBmFkaMBmY6VcNIiJyYX7upP418D3nXHltDc1supmtNbO1BQUF3lcmIiK+TvedBSw0M4AU4FozK3PO/a16Q+fcLGAWQFZWlmvMIkVEWirfAsI5l/npdTN7HvhHsHAQERF/eDnMdQEwEUgxszzgB0A0gHNO+x1ERMKcZwHhnLutDm3v9aoOERGpHx1JLSIiQSkgREQkKAWEiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFAKCBERCUoBISIiQSkgREQkKAWEiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFAKCBERCUoBISIiQSkgREQkKAWEiIgEpYAQEZGgPAsIM5tjZvlmtuUCy+8ws82By3IzG+JVLSIiUnderkE8D1xdw/J9wATn3GDgR8AsD2sREZE6ivLqiZ1zH5hZRg3Ll1e5uRLo6lUtIiJSd+GyD2Iq8LrfRYiIyP/n2RpEqMzsMioDYlwNbaYD0wHS09MbqTIRkZbN1zUIMxsMzAYmOeeKLtTOOTfLOZflnMtKTU1tvAJFRFow3wLCzNKBV4G7nHO7/KpDRESC82wTk5ktACYCKWaWB/wAiAZwzs0EHgXaA8+YGUCZcy7Lq3pERKRuvBzFdFsty6cB07x6fRER+WzCZRSTiIiEGQWEiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFAKCBERCUoBISIiQSkgREQkKAWEiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFAKCBERCUoBISIiQSkgREQkKAWEiIgEpYAQEZGgFBAiIhKUZwFhZnPMLN/MtlxguZnZb8ws28w2m9lwr2oREZG683IN4nng6hqWXwP0DlymA896WIuIiNSRZwHhnPsAOFpDk0nAXFdpJdDGzDp7VY+IiNSNn/sg0oADVW7nBe4TEZEw4GdAWJD7XNCGZtPNbK2ZrS0oKPC4LBERAX8DIg/oVuV2V+BgsIbOuVnOuSznXFZqamqjFCci0tL5GRCLgLsDo5nGAMedc4d8rEdERKqI8uqJzWwBMBFIMbM84AdANIBzbiawGLgWyAbOAFO8qkVEROrOs4Bwzt1Wy3IHPOjV64uIyGejI6lFRCQoBYSIiASlgBARkaAUECIiEpQCQkREglJAiIhIUAoIEREJSgEhIiJBKSBERCQoBYSIiASlgBARkaAUECIiEpQCQkREglJAiIhIUAoIEREJKqSAMLNXzOwLZqZAERFpIUL9h/8scDuw28x+bmb9PKxJRETCQEgB4Zxb4py7AxgO7AfeNrPlZjbFzKK9LFBERPwR8iYjM2sP3AtMAzYAT1EZGG97UpmIiPgqpHNSm9mrQD9gHnCdc+5QYNGfzWytV8WJiIh/QgoIYLZzbnHVO8ws1jl3zjmX5UFdIiLis1A3Mf04yH0ranuQmV1tZjvNLNvMHgmyPNnMXjOzTWa21cymhFiPiIh4rMY1CDPrBKQB8WY2DLDAotZAQi2PjQSeBj4P5AFrzGyRc25blWYPAtucc9eZWSqw08z+5Jw7X7+3IyIiDaW2TUxXUbljuivwZJX7TwLfr+Wxo4Bs59xeADNbCEwCqgaEA5LMzIBE4ChQFmrxIiLinRoDwjn3AvCCmd3gnHuljs+dBhyocjsPGF2tze+ARcBBIAm4xTlXUf2JzGw6MB0gPT29jmWIiEh91LaJ6U7n3ItAhpl9q/py59yTQR72r4cHuc9Vu30VsBG4HOhJ5fEVy5xzJ6q9zixgFkBWVlb15xAREQ/UtpO6VeBnIpXf8KtfapIHdKtyuyuVawpVTQFedZWygX1UDqcVERGf1baJ6feBnz+sx3OvAXqbWSbwCXArldN1VJULXAEsM7OOQF9gbz1eS0REGliok/U9YWatzSzazN4xs0Izu7OmxzjnyoCHgDeB7cBLzrmtZjbDzGYEmv0IuNjMPgbeAb7nnCus/9sREZGGEuqBclc6575rZpOp3HR0E/Ae8GJNDwocXLe42n0zq1w/CFxZp4pFRKRRhHqg3KcT8l0LLHDOHfWoHhERCROhrkG8ZmY7gLPAVwMHtZV4V5aIiPgt1Om+HwHGAlnOuVLgNJUHvYmISDMV6hoEQH8qj4eo+pi5DVyPiIiEiVCn+55H5YFsG4HywN0OBYSISLMV6hpEFjDAOaejmEVEWohQA2IL0Ak4VFtDaf7mr8r17LlvH625tkTCRagBkQJsM7PVwLlP73TOXe9JVSIi4rtQA+IxL4sQEZHwE1JAOOfeN7PuQG/n3BIzSwAivS1NRET8FOpcTPcDLwO/D9yVBvzNo5pEwk55haO0vAKN05CWJNRNTA9SeYa4VQDOud1m1sGzqkR8VF7h2Ftwil1HTpJ79AwFp85RUlp5HqsIg7YJMXROjqN3hyT6d2lNYmxdDicSaTpC/WSfc86drzwzKAQOltNXKWlWzpwvY8WeIlbvP8rJkjKiIoxu7RIY0rUNSXFRRJpRUlZB0alzHCg+y5aDJ1i06SADurRmYt9UOifH+/0WRBpUqAHxvpl9H4g3s88DXwVe864skcZTWl7B8uxClu4q4FxZBX07JpE1pC29OyQRExV8K6xzjsMnSlifU8zanGI+/uQ4Q7u14fMDOpKaFNvI70DEG6EGxCPAVOBj4AEqp/Ce7VVRIo3lk2NneWnNAQpOnaN/pyQ+P6ATnZLjan2cmdE5OZ4vDI7n8n4d+WB3AR/uLuSKXy7lJ5MHcd2QLo1QvYi3Qh3FVGFmfwP+5pwr8LYkEe9VOMey3YUs2XaEVrGR3HtxBn061nYW3eDiYyK5amAnhqe3ZemufB5esIEVe4v44fUDiY4MdUZ9kfBT46fXKj1mZoXADmCnmRWY2aONU55Iwzt7vpznP9rPm1sP069zEl+7vHe9w6Gq1KRYXnpgLDMm9GT+qlzue34NJ0pKG6BiEX/U9vXmG8AlwEjnXHvnXDtgNHCJmX3T6+JEGtrR0+eZ+cEe9hWeZvLQNG4flU5CA45Cio6M4JFr+vHEDYNZsaeIG59dTl7xmQZ7fpHGVFtA3A3c5pzb9+kdzrm9wJ2BZSJNxvrcYp5dms2pkjKmjMtgZGY7Ph2Z19BuHtmNF+4bxaHjJdzy+5UKCWmSaguIaOdcYfU7A/shooO0FwlLy7MLueMPq4iNjmTGhJ70SEn0/DUv6ZXCgvvHcLKklDtmr+LwcZ2EUZqW2gLifD2XAWBmV5vZTjPLNrNHLtBmopltNLOtZvZ+bc8pUlcf7CpgyvNrSG+XwAOX9mjUYagXpSXzwn2jKDp1nttnr6Tg5LnaHyQSJmoLiCFmdiLI5SQwqKYHmlkk8DRwDTAAuM3MBlRr0wZ4BrjeOTcQuKm+b0QkmPd25DPthbX0SE1kwfQxJMU1/orvsPS2zLl3JIeOlXDPnNWcPlfW6DWI1EeNAeGci3TOtQ5ySXLO1faXNgrIds7tdc6dBxbyn+exvh141TmXG3i9/Pq+EZHqPsou5IF56+jTKZEF94+mXasY32oZldmOZ+8czo7DJ/j6wg2UV2giAgl/Xg7STgMOVLmdF7ivqj5AWzNbambrzCzojm8zm25ma81sbUGBDsOQ2q3PLeb+uWvJTGnFi1NH0ybBv3D41MS+HXjs+oEs2Z7PzxZv97sckVp5OctYsOEh1b82RQEjgCuAeGCFma10zu36twc5NwuYBZCVlaWvXlKjHYdPcO+c1aQmxTJv6qiwCIdP3T02g70Fp5n94T56pCbqDHoS1rwMiDygW5XbXYGDQdoUOudOA6fN7ANgCLALkXrIKz7DXc+tJiEmihenjqZD69qnzWhs//OF/uwvOs0PFm2hX+ckhqe39bskkaC83MS0BuhtZplmFgPcCiyq1ubvwHgziwqchGg0oHVvqZfjZ0uZ8sc1lJSWM3fqKLq1S/C7pKCiIiN46pZhdEqO48E/rafolEY2SXjyLCCcc2XAQ8CbVP7Tf8k5t9XMZpjZjECb7cAbwGZgNTDbObfFq5qk+TpfVsFXXlzH/qLT/P6uEQ0ydYaXkhOiefaOERSdPs/XF27UTmsJS57OJOacW+yc6+Oc6+mc+0ngvpnOuZlV2vzCOTfAOXeRc+7XXtYjzZNzjkde3czyPUU8fsNgLu6Z4ndJIbkoLZkfT7qID7ML+dXb2qoq4UdTTUqT99Q7u3l1/Sd883N9+PLwrn6XUyc3j+zGzVldeXppNh9l/8ekBSK+UkBIk/byujx+vWQ3N47oyteu6OV3OfXy2PUD6ZHSim/+eSNHT9c6QYFIo1FASJO1PLuQR17ZzCW92vPTyYM8m3jPawkxUfzmtmEcO1PKd1/ehHPaHyHhQQEhTdKuIyd54MV19EhtxTN3jLjgqUGbioFdkvneNf1Ysj2feStz/C5HBFBASBOUf7KEKX9cQ1x0JHPuHUlyfPOYWPi+SzKY2DeVH/9zOzsPn/S7HBEFhDQtp8+VMfX5tRSfOc8f7x1J17bheaxDfZgZ/3vTEFrHRfPwgvWUlJb7XZK0cAoIaTLKKxxfX7iBrQeP89vbhnFRWrLfJTW4lMRYnrx5CLuOnOKnmq9JfKaAkCbBOccPX9vKku35PHb9QK7o39HvkjxzaZ9Upo7LZO6KHN7boQmOxT8KCGkSZi/bx9wVOUy/tAd3j83wuxzPfeeqvvTrlMR3Xt5EoabiEJ8oICTsLf74ED9ZvJ0vDOrMI1f387ucRhEXHclvbhvGiZIyvvvyZg19FV8oICSsrcs5yjf+vJER3dvyy5uHEBHRNI91qI8+HZP4/jX9eHdHPi9q6Kv4QAEhYWtf4WmmvbCWtDbx/OHuLOKiI/0uqdHdc3EGE/pUDn3NztfQV2lcCggJS0dPn2fKH1djZvzx3pG+ni7UT2bGL24aTKvYKL62YCPnyjT0VRqPAkLCTklpOdNeWMOh4yX84e4sMlJa+V2SrzokxfHEDYPZdugET76lWV+l8SggJKyUlVfw0Pz1bDhwjF/fMpQR3XW2NYDPDejI7aPTmbVsL8s166s0EgWEhI0K5/jeKx+zZHs+/3fSRVwzqLPfJYWV//lCfzJTWvGtlzZx7IxmfRXvKSAkLDjneGPLYV5Zn8e3Pt+Hu8Z097uksJMQE8VTtwyj8NQ5vv/XjzX0VTyngJCw8MGuAj7MLuTeizN4+PKmeV6HxjCoazL/dWVfFn98mJfX5fldjjRzCgjx3Zr9R3lz2xGGdE3m0S8OaLLndWgs0y/twejMdjy2aCs5Raf9LkeaMQWE+GrLJ8f524ZP6NMxkRtHdGtRB8LVV2SE8atbhhIZYXx94UZKyyv8LkmaKU8DwsyuNrOdZpZtZo/U0G6kmZWb2Y1e1iPhJTv/FH9ee4Bu7RK4fVR3IhUOIevSJp6fTB7ExgPH+O272X6XI82UZwFhZpHA08A1wADgNjMbcIF2jwNvelWLhJ+9BaeYt3I/qYmx3D22e5M/I5wfrhvShS8PS+N37+5m5d4iv8uRZsjLv8pRQLZzbq9z7jywEJgUpN3DwCuA5jVuIfYXnmbuihzaJsRw37hMEmKi/C6pyfrhpIFktG/FQ/M3kH+ixO9ypJnxMiDSgANVbucF7vsXM0sDJgMza3oiM5tuZmvNbG1BQUGDFyqNJ7foNM+v2E/r+GimjsskMVbh8FkkxUXz7J0jOH2ujAfnr9f+CGlQXgZEsA3K1Qdu/xr4nnOuxglmnHOznHNZzrms1NTUhqpPGlle8Rn+uHw/SbFRTBuXSVJc8ziXtN/6dkriZ18exJr9xTz++g6/y5FmxMuvb3lAtyq3uwIHq7XJAhYGhjWmANeaWZlz7m8e1iU++OTYWeZ8tI+EmEimjsukdbzCoSF9aVga63OLmf3hPoZ3b8u1OgpdGoCXaxBrgN5mlmlmMcCtwKKqDZxzmc65DOdcBvAy8FWFQ/Nz6PhZ5ny4j7ioSKaN60GbhJY5M6vX/ucLAxjarQ3f+csm9hSc8rscaQY8CwjnXBnwEJWjk7YDLznntprZDDOb4dXrSnjJKz7D7GX7iImKYNr4HrRtodN2N4aYqAieuWM4sdGRTJ+7luNnS/0uSZo4T8cWOucWO+f6OOd6Oud+ErhvpnPuP3ZKO+fudc697GU90rhyi07z3If7iIuO4P7xPVrsOR0aU5c28Tx9+3Byis7w0Pz1lGmntXwGGkIinthbeIq5y3NIioti6rjMFrNZaf6qXL9LAOD6IV14dcMn3PncKq4fklb7AxrB7aPT/S5B6kgBIQ1u95GTvLgqhzYJMZU7pDVaqdFlZbSj4OQ5lmUXkpoYy9ieKX6XJE2QAkIa1I5DJ/jT6lxSE2O5T8c5+OqqizpReOoc/9h8iMS4aAalJftdkjQxmt9AGsyWT47zp1W5dGodx7TxCge/RZhxy8h0urVL4KW1BzSySepMASENYtOBYyxck0ta23imavqMsBETFcE9YzNo3yqGeStz+OTYWb9LkiZEASGf2bqcYl5ae4Du7Vsx5eIM4qIj/S5JqoiPiWTKJZkkREfyx4/2cfi45myS0Cgg5DNZta+IV9bn0bNDIveMzSBW4RCWkuOjuW9cJlERxuwP93LouNYkpHYKCKm3j7IL+fvGg/TrlMRdYzRld7hLSYxl2vgeREUYz324TyEhtdJftNTL0p35/PPjQwzs0prbR6cTHamPUlNQNSRmL9tH7tEzfpckYUx/1VInzjne2HKYt7YdYWi3Ntw6Mp2oCH2MmpKUxFjuH9+D+JhInvtwLzsOn/C7JAlT+suWkFVUOB79+1Y+2F3AqMx23Diiq04T2kS1T4zlgUt7kJoUy4src1iXc9TvkiQMKSAkJGXlFXz7L5uYtzKH8b1TmDSkCxGmcGjKkuKiuX9cD3qkJvLK+k94fcshKlz1U7ZIS6bB6lKrc2XlfH3BRt7Yepj/+nwf2rWKwRQOzUJsdCR3j+3OPzcfYtnuQo6cKOGWrHTiYzQaTbQGIbU4e76c++eu442th3n0iwN4+IreCodmJioigklD0/jS0DT25J/mmaXZHNQBdYICQmpwoqSUu+esYtnuAp64YTD3jcv0uyTx0KjMdkwdl0lpeQXPvr+H5XsKcdrk1KIpICSo4tPnueMPq9iQe4zf3DqMm0d2q/1B0uRlpLTi4ct707tDIv/YfIh5K3M4WaITD7VUCgj5D/knSrhl1gp2HjnJrLtHcN2QLn6XJI2oVWwUd43pzhcHdyY7/xS/XrKbDbnFWptogRQQ8m8OHD3DTb9fwSfFZ3l+ykgu79fR75LEB2bGxT1TeOjyXqQmxfKXdXnMW5lD8enzfpcmjUgBIf+yp+AUN/9+BcWnz/PitNFcrJPMtHgdkuKYfmkPvjCoM3sKTvGrJbtYsv0IpTqVaYugYa4CwLaDJ7jruVWYwZ8fGEv/zq39LknCRIQZl/RKYWCX1ry+5TDv7shnfW4x117UmYFdWmtUWzPm6RqEmV1tZjvNLNvMHgmy/A4z2xy4LDezIV7WI8Gtyynm1lkriImKUDjIBbVJiOG2UelMG5dJbFQE81fn8txH+8gr1nxOzZVnAWFmkcDTwDXAAOA2MxtQrdk+YIJzbjDwI2CWV/VIcMt2F3DXc6to2yqGv8wYS8/URL9LkjDXIzWRhy7rzXWDO3P4eAnPLN3D/FU5FJw853dp0sC83MQ0Csh2zu0FMLOFwCRg26cNnHPLq7RfCXT1sB6p5rVNB/nWSxvpmZrI3PtG0aF1nN8lSRMRGWGM7ZnC8PS2LMsu5MPsQrYd2sWI7m25rG8H2iTE+F2iNAAvAyINOFDldh4wuob2U4HXgy0ws+nAdID09PSGqq9Fm7diP48u2srI7u34wz1ZJMdH+12SNEGx0ZF8rn9HxvRoz9Kd+azae5T1OccYkdGWiX1SFRRNnJcBEWzPVdCB1GZ2GZUBMS7YcufcLAKbn7KysjQY+zNwzvHrJbt56p3dfK5/B353+3CdIlQ+s8TYKL44uAvjeqXw/q4C1u4vZt3+YkZ0b8uEvqm0VVA0SV4GRB5Q9fDbrsDB6o3MbDAwG7jGOVfkYT0tXkWF47HXtjJ3RQ43jujKz788iCid6EcaUJuEGCYNTWNCn9TKoMgpZl1OMcO7t+XSPil0bZvgd4lSB17+d1gD9DazTDOLAW4FFlVtYGbpwKvAXc65XR7W0uKdKyvnaws3MHdFDtMv7cEvbhyscBDPfBoU376yLyMz27I+t5iJv1jKf7+6mQM6i12T4dkahHOuzMweAt4EIoE5zrmtZjYjsHwm8CjQHngmMJa6zDmX5VVNLdWxM+eZPm8dq/cd5ZFr+jFjQk+/S5IWIjk+muuHpDGhTwcOHz/LgtUH+MvaPG4Y3pWHLu9Ft3Zaowhnnh4o55xbDCyudt/MKtenAdO8rKGlyy06w73Prybv6FmeunUok4am+V2StEDJ8dF8ZWJPvjKxFzPf38P81bm8sj6Pm7K68uBlvbTpKUzpSOpmbOOBY0x7YQ2l5Y55U0cxukd7v0uSFq5TchyPXT+QGRN68uzSbBasPsDL6/K4dWQ6D17Wi07JGmodTrQRupl6Y8shbp21gviYSF796sUKBwkrnZLj+OGki1j6nYnclNWNBatzufQX7/HD17aSf7LE7/IkQAHRzFRUOH719i5mvLiefp1a89evXqKjoyVsdWkTz08nD+K9b09k8tA05q7I4dIn3uOni7dTdEpHZvtNAdGMnCwpZfq8dTz1zm5uGN6VhdPHkJIY63dZIrXq1i6Bx28czDvfmsC1gzoze9lexj/xHk+8sUNTjPtIAdFM7C04xeRnlvPeznx+cN0A/vemwToATpqcjJRWPHnzUN765gQ+178jz76/h/FPvMeTb+3k+Fmd2a6xKSCagTe2HGbS0x9RdOoc86aOYsolmZqCWZq0Xh0S+c1tw3jzG5dyaZ8UfvNuNuMff5ffvrObU+fK/C6vxdAopiaspLScH/9zGy+uzGVQWjLP3DFc48qlWenTMYln7hjB1oPH+dXbu/nl27uY89E+HpjQk7vHdichRv/CvKTebaJ2HznJwws2sOPwSe4fn8l3rupHTJRWCKV5Gtglmdn3ZLHpwDF+tWQXP399B7OX7WXGhJ7cOaa7Nqd6RAHRxDjnmL86lx/9YxuJsVE8P2UkE/t28LsskUYxpFsbnp8yinU5R3ny7V38+J/b+cOyvTx4WS9uGdmN2CgFRUNSQDQhB46e4ZFXN/NRdhHje6fwy5uH0CFJBxZJyzOiezv+NG0MK/cW8eRbu3j071uZuXQPD13emxtHdNXadANRQDQBZeUVzF2Rwy/e3ElkhPHTyYO4dWQ3IiK0I1patjE92vPnB8bwYXYhv3xrF9//68f87t3dTB3fg1tHdqNVrP7FfRbqvTC3am8RP1i0lR2HTzKxbyo/nTyILm3i/S5LJGyYGeN7pzKuVwpLdxXw7NI9/Ogf2/jtu7u5Z2wG91ycQbtWOh9FfSggwlRu0Rl+8dZOXtt0kLQ28cy8czhXDeyk4asiF2BmXNa3A5f17cC6nKM8u3QvT72zm1kf7OWWkd2YOi5To/zqSAERZvJPlPDbd7NZsDqXqEjja5f34isTexEfo51vIqEa0b0ds+9px64jJ5n5/h5eXJnDCyv2c3nfDtx9cQbje6VoE20IFBBh4sDRM/xh2V5eWnuAsnLHLSO78bUretOxtXZCi9RXn45JPHnzUL59ZV/mr8pl4Zpc7pmzmoz2Cdw5pjtfGpam6WhqoIDwkXOOtTnFzF2Rw+KPDxFhMHlYGl+d2IuMlFZ+lyfSbHRpE8+3r+rLw1f04o0th5m7Iocf/3M7P3t9BxP7pDJ5eBqf699Rx1NUo4DwQeGpc7y26SDzV+WyO/8USbFR3HdJBlPH9dB8+CIeio2KZNLQNCYNTWPn4ZO8uiGPv284yDs78kmKi+KqgZ24ckBHxvdO1WZdFBCNJv9kCUt3FPDa5oN8lF1IhYMhXZN5/IZBXDeki6YMEGlkfTsl8d/X9Oe7V/VjxZ4iXt2Qx5tbD/PyujzioiMY1yuVKwd0ZFzvlBY7clD/lTxyvqyCdTnFvL+rgA92FbDt0AkA0tsl8JWJPbluSBf6dWrtc5UiEhlhjOudwrjeKZSWV7B631He3naEt7YeZsn2IwB0b5/AmMz2jO3ZnpGZ7eiSHNciRhQqIBpAeYUjp+g0m/OOs/HAMTblHWPrwROcL6sgKsIY3r0t37mqLxP6pDKwS+sW8cESaYqiIyO4pFcKl/RK4QfXDWDH4ZMs31PEij1FvL7lEH9eewCA9q1iuCgtmUFpyVyUlkzfTkl0axtPVGTzOoLb04Aws6uBp4BIYLZz7ufVlltg+bXAGeBe59x6L2uqrzPnyzh0vITDx0s4eOwsOUVn2FNwir0Fp9lXdJrzZRUAxEdHMigtmXvGdicrox0X92xPUly0z9WLSF2ZGf07t6Z/59ZMHZdJeYVj+6ETrMsp5uNPjrPlk+N8mF1IeYUDIDrSSG+XQI/URDJTWtE5OY5OrePolFx5SU2MbXIB4llAmFkk8DTweSAPWGNmi5xz26o0uwboHbiMBp4N/GxwJ0tKySs+y9nSckoCl7PnKyp/Bm6fOlfGsTOlHD9byrEz5zl2tpTjZ0opPHWOEyX/Pgd9ZETlh6Fnaism9E2lV2oig7om07tDYpP7EIhI7SIjjIsCawyfKiktZ/uhE2Tnn2Jv4Wn2Br40vr+r4F9fGj8VYZCSGEubhGjaxMfQOj6a5CqXVrGRxEZHEh+4xEVHVP6MiSQuKpKYKKNdq9hGPSrcyzWIUUC2c24vgJktBCYBVQNiEjDXOeeAlWbWxsw6O+cONXQx7+8q4KH5G2ptlxQX9a9fYJuEaNLaxNOuVQydkuMC3wji6ZQcR1qbeE0IJtLCxUVHMiy9LcPS2/7b/c45is+Ucuj4WY6cKOHQ8RKOHC/h8ImSwBfQUvKKz7DtYOUX0tPny0N6vQcm9OC/r+nvxVsJysuASAMOVLmdx3+uHQRrkwb8W0CY2XRgeuDmKTPb2bClhiQFKPThdWvTrOq6w4NCqmlW/dUIGqyuBv7dNvv+Cub7j8P36/fQFKB7XR/kZUAE2xPr6tEG59wsYFZDFFVfZrbWOZflZw3BqK66UV11o7rqJszryqjr47zcRpIHdKtyuytwsB5tRETEB14GxBqgt5llmlkMcCuwqFqbRcDdVmkMcNyL/Q8iIlJ3nm1ics6VmdlDwJtUDnOd45zbamYzAstnAoupHOKaTeUw1yle1dMAfN3EVQPVVTeqq25UV900q7qscgCRiIjIv9M4TRERCUoBISIiQSkgLsDMbjKzrWZWYWYXHLZmZvvN7GMz22hma8OorqvNbKeZZZvZI41QVzsze9vMdgd+tr1AO8/7q7b3HhgU8ZvA8s1mNtyLOupR10QzOx7om41m9mgj1TXHzPLNbMsFlvvVX7XV1ej9ZWbdzOw9M9se+Dv8epA2jd5fIdZV9/5yzukS5AL0B/oCS4GsGtrtB1LCqS4qBwXsAXoAMcAmYIDHdT0BPBK4/gjwuB/9Fcp7p3JgxOtUHoczBljVCL+3UOqaCPyjsT5LVV73UmA4sOUCyxu9v0Ksq9H7C+gMDA9cTwJ2hcnnK5S66txfWoO4AOfcduecH0ds1yjEuv41zYlz7jzw6TQnXpoEvBC4/gLwJY9f70JCee//muLFObcSaGNmncOgLl845z4AjtbQxI/+CqWuRuecO+QCE4o6504C26mc/aGqRu+vEOuqMwXEZ+eAt8xsXWBKkHBwoSlMvNTRBY5hCfzscIF2XvdXKO/dj/4J9TXHmtkmM3vdzAZ6XFOo/OivUPnWX2aWAQwDVlVb5Gt/1VAX1LG/WvT5IMxsCdApyKL/45z7e4hPc4lz7qCZdQDeNrMdgW8+ftYV0hQmdVVTXXV4mgbvr2oabIqXBhbKa64HujvnTpnZtcDfqJzp2G9+9FcofOsvM0sEXgG+4Zw7UX1xkIc0Sn/VUled+6tFB4Rz7nMN8BwHAz/zzeyvVG5K+Ez/8BqgLk+mMKmpLjM7YoGZeAOr0/kXeI4G769qwnWKl1pfs+oftHNusZk9Y2Ypzjm/J6ULyylx/OovM4um8p/wn5xzrwZp4kt/1VZXffpLm5g+AzNrZWZJn14HrgSCjrhoZKFMc9LQFgH3BK7fA/zHmk4j9Ve4TvFSa11m1sms8nSDZjaKyr/PIo/rCkVYTonjR38FXu85YLtz7skLNGv0/gqlrnr1l9d715vqBZhM5TeBc8AR4M3A/V2AxYHrPagcjbIJ2ErlJiDf6wrcvpbKkQx7Gqmu9sA7wO7Az3Z+9Vew9w7MAGYErhuVJ7PaA3xMDaPUGrmuhwL9sglYCVzcSHUtoHKK/dLAZ2tqmPRXbXU1en8B46jcXLQZ2Bi4XOt3f4VYV537S1NtiIhIUNrEJCIiQSkgREQkKAWEiIgEpYAQEZGgFBAiIhKUAkJERIJSQIiISFD/D55NxcC3iPFpAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.distplot(pd.DataFrame(arr_ex1.reshape(9,1)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "id": "7ad93dc8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "F:\\DS\\anaconda3\\lib\\site-packages\\seaborn\\distributions.py:2557: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).\n",
      "  warnings.warn(msg, FutureWarning)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:ylabel='Density'>"
      ]
     },
     "execution_count": 108,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAD4CAYAAADhNOGaAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAArg0lEQVR4nO3deXxU9b3/8dcn+76vTEISdsIOYVUUFQRsrWhda/Xa6qU+ql1sb6/e5Xdvr+1tb+u9drEupZa617oXFaW4AoJI2DeBEBKyELJA9j35/v6YwUZMyCTk5MzyeT4e88jMnHMm70xO8pnvOd/v94gxBqWUUv4rwO4ASiml7KWFQCml/JwWAqWU8nNaCJRSys9pIVBKKT8XZHeAgUpKSjLZ2dl2x1BKKa+yffv2amNMcm/LvK4QZGdnk5+fb3cMpZTyKiJS3NcyPTSklFJ+zrJCICKrRaRSRPb1s95sEekSkWutyqKUUqpvVrYIngCWnWsFEQkEfgGsszCHUkqpc7CsEBhjNgCn+lntO8DLQKVVOZRSSp2bbecIRMQBXA08ZlcGpZRS9p4s/jVwrzGmq78VRWSliOSLSH5VVZX1yZRSyo/Y2X00D3heRACSgCtEpNMY89rZKxpjVgGrAPLy8nS6VKWUGkK2FQJjTM6Z+yLyBPBGb0VAKaWUtSwrBCLyZ2ARkCQipcB/AsEAxhg9L6CUUh7CskJgjLlpAOveZlUOpYbTc1uP2x3BFl+bO9LuCOo86MhipZTyc1oIlFLKz2khUEopP6eFQCml/JwWAqWU8nNaCJRSys9pIVBKKT+nhUAppfycFgKllPJzWgiUUsrPaSFQSik/p4VAKaX8nBYCpZTyc1oIlFLKz2khUEopP6eFQCml/JwWAqWU8nNaCJRSys9pIVBKKT+nhUAppfycFgKllPJzWgiUUsrPWVYIRGS1iFSKyL4+lt8sIntct80iMs2qLEoppfpmZYvgCWDZOZYfAy42xkwFfgKssjCLUkqpPgRZ9cLGmA0ikn2O5Zt7PPwYyLAqi1JKqb55yjmC24G3+looIitFJF9E8quqqoYxllJK+T7bC4GIXIKzENzb1zrGmFXGmDxjTF5ycvLwhVNKKT9g2aEhd4jIVOBxYLkxpsbOLEop5a9saxGIyEjgFeAWY8xhu3IopZS/s6xFICJ/BhYBSSJSCvwnEAxgjHkM+A8gEXhERAA6jTF5VuVRSinVOyt7Dd3Uz/I7gDus+v5KKaXcY/vJYqWUUvbSQqCUUn5OC4FSSvk5LQRKKeXntBAopZSf00KglFJ+TguBUkr5OS0ESinl57QQKKWUn7N10jnlm57betzuCEqpAdAWgVJK+TltESjlAzq7uyk51cLxmiZqmtpp6egCIDosmNSYUEYnR5EUFWpzSuWptBAo5cVO1reypbCGvaV1n/3zjwoNIiIkEICCykbaOrsByIgPZ/6oRKZlxhHgnPFXKUALgVJeqbqxjXX7K9hfXk9woDBpRCyTRsSQkxRJRMjf/6yNMZxqaufTiga2FZ3ixe2lbDxSzYoZDkYmRNj4EyhPooVAKS/S1W344FAlHxyqIjBQuHRCCgtGJRIR2vufsoiQGBXKBWNCWTA6kb1ldby9r4JVG45y6YQUFo1P0daB0kKglLeorG/lxe2llNW2MD0zjuWT04gOC3Z7exFhakYc41KjWbO7nHcOVlJR38Z1szIIDtR+I/5MC4FSXiC/6BRrdpcTEhTA1+aMZLIjdtCvFRYcyHWzMkiPDePtfRW0tHdyy7xsQoK0GPgrLQRKebCubsPavSfYUljDmJQorpuVMaBWQF9EhIVjk4kMDeLl7aU8s7WYW+dnERSgxcAfaSFQykM1t3fy3CfHKaxq4sIxSSydlEZgwNAez585Mh5jDC/vKOPVHWVcOysD0XMGfkcLgVIeqL61g9WbjlHT1M61szKYOTLesu81KyuB2pYO3j1YSXJ0KIvGp1j2vZRn0kKglIc53dTOHz86RmNbJ99YkM2o5CjLv+el41Ooamhj/YGTZCZEMHoYvqfyHJYdEBSR1SJSKSL7+lguIvJbESkQkT0iMtOqLEp5i8qGVn6/4Sgt7V3cfkHOsBQBcJ4zuHqGg6SoUJ7fVkJjW+ewfF/lGaw8M/QEsOwcy5cDY123lcCjFmZRyuOV17bwhw2FdBu4Y2EOmcM84Cs0KJCb5o6kraOLV3eWYYwZ1u+v7GNZITDGbABOnWOVq4CnjNPHQJyIpFuVRylPVlzTxOObCgkKDGDlwlGkx4bbkiMtJowluakcPFHPzuO1tmRQw8/OvmIOoKTH41LXc18gIitFJF9E8quqqoYlnFLDpaCykdUfHSMyJIhvXTSKpGh7J4e7YEwSWQkRvLn3hB4i8hN2FoLe+qj12hY1xqwyxuQZY/KSk5MtjqXU8Dl4op4ntxSRGBnKyotGERcRYnckAkRYMcNBe2c3b+09YXccNQzsLASlQGaPxxlAuU1ZlBp2u0pqeXZrMemxYdyxMGdIBooNldSYMBaOS2JnSS3FNU12x1EWs7MQrAFudfUemgfUGWP044fyC58cO8WL+SVkJUZy+wU5n5sx1FMsGpdCTFgQa/ee0BPHPs7K7qN/BrYA40WkVERuF5E7ReRO1yprgUKgAPgD8G2rsijlSTYeqeK1XWWMS43mtgXZhAYH2h2pVyFBASzJTaXkdAt7y+rsjqMsZNnHEGPMTf0sN8BdVn1/pTyNMYa/HTjJh4ermOyI5fq8DI+f22fGyHg+Kqhh3f4KctNjCNJZSn2S/laVGgZd3YZXdpbx4eEqZmcncOPsTI8vAuA8cbx8Shqnmzv4uLDG7jjKIp6/Jyrl5Tq6unluazHbi09zyfgUVkwf4VUXgxmbEs241CjeO1RJS3uX3XGUBbQQKGWhlvYuVn90jE8rGrhy2giW5KZ65eyeSyel0drRzeaj1XZHURbQQqCURWoa2/j9hqOUnmrhhtmZzB+VaHekQUuPDSc3PYaPjlbT2qGtAl+jhUApCxytauSRD47S0NrJbRdkMzUjzu5I5+2S8Sm0dnSzVc8V+BwtBEoNIWMMW45W86ePjhEdFsS3F432mSmdHfHhjEuNYmNBNe2d3XbHUUNIC4FSQ6SlvYvnPjnO63tOMC41mjsvHk1ilL3zBg21S8en0NzexSdF55pPUnkbzxvOqJQXKqpu4oX8EupbO1g+OY0LxiR5Vc8gd41MjGRUciQbj1QxNyeBYB1X4BP0t6jUeWjt6GLN7jL+sLGQgADhzotHs3Bssk8WgTMuGZ9CQ2snu0pq7Y6ihoi2CJQaBGMM+8vreWNPOQ2tncwblcjluakeO13EUBqVFEl6bBgfFVSTlxXvld1h1edpIVBqgAqrGlm3v4KS0y2kx4Zx89ysYb+amJ1EhAvGJPHS9lIKqhoZmxJtdyR1nrQQKOWGbmM4crKBjwpqKKhqJCYsiKunO5iZFU9ggP99Ip7qiOXtfRVsLqjRQuADtBAodQ71LR3sKatja2ENNU3tRIcGsXxyGvNGJfr1idKgwADmjkrg3YOVVDa02h1HnSctBEr1YIyhprGdI5UN7C2rp7imCQOMTIhg8cRUJjlivGKyuOEwNyeRDw9VseVoDd9fbHcadT60ECi/1tzeyYm6VirqWimvbaGwuom6lg4AUqJDuXRCCpMdsaTGhNmc1PNEhQYxLTOOHcdPU9vc7hGX2VSDo4VA+YVuY6hubKOirvWzf/wV9a2f/dMHiAwNIicxgkXjkxmdHEWSjw0Gs8KC0YlsLz7NS9tLuWPhKLvjqEHSQqB8TrcxVDW0UVbbQtnpFspqWzhR10JHl/NyiwECydGh5CRFkhYTRlpsGOmxYR51zWBvkR4bTlZCBM9uPc7tF+ZoV1IvpYVA+YTa5nYOnWzgyMlGjlY10uaaCyckMIARcWHMyU4gPTactNgwUqJD9UpbQ2hOTgIvbi9ly9EaFoxJsjuOGgQtBMprtXZ0sbesjp3HT1NU0wxAXHgwUzNiyU6MxBEXTlJ0qE+P8vUEkx2xrD94kme3HtdC4KW0ECivU9fSwaYjVXxSdIqOLkNyVCiX56aSOyKG5KhQPTwxzIIDA7h2ZgZPbC6isqGVlGg9se5t3CoEIvIysBp4yxij888qWzS2dfLOwZNsLz6NMYbpmXHMG5WIIy5c//nb7Ka5I3l80zFezC/lrkvG2B1HDZC7B0ofBb4GHBGR/xGRCe5sJCLLROSQiBSIyH29LI8VkddFZLeI7BeRbwwgu/IT3cbwybFT/Gr9YbYXnWZWVjw/WDKea2dlkhEfoUXAA4xOjmLB6ESe23qcrm5jdxw1QG4VAmPMO8aYm4GZQBGwXkQ2i8g3RKTXrhYiEgg8DCwHcoGbRCT3rNXuAg4YY6YBi4D/ExHtjKw+U9PYxqoNhby2q4y02DC+c+kYVkx3kBCpu4mnuXluFmW1LWw4XGV3FDVAbnedEJFE4DbgDmAn8BuchWF9H5vMAQqMMYXGmHbgeeCqs9YxQLQ4P9JFAaeAzoH8AMp37S+v43fvF1DV0MZ1szK448IcUnRgl8dakptKQmQIL+SX2B1FDZC75wheASYATwNXGmNOuBb9RUTy+9jMAfTcI0qBuWet8ztgDVAORAM39HYOQkRWAisBRo4c6U5k5cW6ug3r9lewqaCajPhwbpozkngdterxQoICWDHdwdMfF3GqqV1bbV7E3RbB48aYXGPMz88UAREJBTDG5PWxTW8Hbs8+eLgU2AWMAKYDvxORmC9sZMwqY0yeMSYvOTnZzcjKG3V0dfPcJ8fZVFDNvFEJrFw4SouAF7kuL4OOLsNfd5XZHUUNgLuF4Ke9PLeln21KgcwejzNwfvLv6RvAK8apADiGs+Wh/FBrRxdPbC7i4Il6rpw2gq9Mc+jALy8zMT2GyY4YXswvtTuKGoBz/pWJSJqIzALCRWSGiMx03RYB/V2JYxswVkRyXCeAb8R5GKin48Blru+VCowHCgf+Yyhv19zWyR83HaO4ponr8zKZPyrR7khqkK7Py+TAiXr2ldXZHUW5qb9zBEtxniDOAB7s8XwD8K/n2tAY0ykidwPrgEBgtTFmv4jc6Vr+GPAT4AkR2YvzUNK9xpjqwfwgynu1dXbxxJYiTta3csu8LManfeHooPIiX5k2gp++cZCXtpcy2RFrdxzlhnMWAmPMk8CTIvJVY8zLA31xY8xaYO1Zzz3W4345cPlAX1f5js7ubp7bepzy2hZunqtFwBfERYSwZFIqr+0q41+umEBokO9fx9nb9Xdo6Ouuu9ki8oOzb8OQT/mwbmN4aXspRyobuXqGg4npWgR8xXWzMqht7uDdg5V2R1Fu6O9MXKTraxTO7p1n35QatPUHTrKntI5lk9KYlZVgdxw1hBaOTSYtJowXdUyBV+jv0NDvXV//a3jiKH+xr6yODw9XMTs7noVjdcZKXxMYIHx1loNHPzjKyfpWvcKbh3Orb56I/FJEYkQkWETeFZHqHoeNlBqQk/WtvLS9lMz4cK6cOkLnCvJR187KpNvAKzt0TIGnc7eT9uXGmHrgyzjHB4wDfmRZKuWzWju6eObjYkKCAvja3CwdJ+DDcpIimZ0dz4vbSzBGJ6LzZO7+FZ6ZWO4K4M/GmFMW5VE+zBjDqzvLON3czk1zRhIbrpeG9HXXzsqgsKqJPaU6psCTuVsIXheRT4E84F0RSQZarYulfNGuklr2ltWxeGIqOUmR/W+gvN6yyemEBAXw6k49POTJ3J2G+j5gPpBnjOkAmvjiTKJK9el0UztrdpeTlRjBReN0vih/ERsezJKJqby+u5yOLr2mlacayAHaicANInIrcC06EEy5qdsYXtju7EZ4/axMvYawn1kxw0FNUzsbj+h1CjyVu9NQPw2MxjlTaJfraQM8ZU0s5Us2HammuKaZ62ZlEK9TE/udi8clEx8RzCs7yrh0QqrdcVQv3L14fR6Qa/TUvxqgmsY23jl4ktz0GKZnxtkdR9kgJCiAL08dwQv5JTS0dhAdpp0EPI27h4b2AWlWBlG+xxjDq7vKCAoUvjJNxwv4s6tnOmjr7OatfRV2R1G9cLcQJAEHRGSdiKw5c7MymPJ+O46fprCqiaWT0ojRrqJ+bUZmHNmJEbymvYc8kruHhn5sZQjlexpaO1i7t4LsxAhmZ+s8Qv5ORFgxw8Fv3j3CiboW0mPD7Y6kenC3++iHQBEQ7Lq/DdhhYS7l5d7eV0F7VzcrZji0l5ACYMV0B8bAX3edfaFCZTd35xr6R+Al4PeupxzAaxZlUl6uuKaJnSW1LBybREq0TjamnLKTIpk5Mo5Xd5TplBMext1zBHcBFwD1AMaYI0CKVaGU9+rqNry+p5yYsCAWjdNdRH3e1TMcHDrZwMETDXZHUT24WwjajDHtZx6ISBDOcQRKfc4L+SWU17ayfIpzagGlevry1BEEBwqv7tSL23sSd/9SPxSRf8V5EfslwIvA69bFUt6orrmDB9YdIjsxgql6rVrVi/jIEBaNT+Gvu8rp6tbPkp7C3UJwH1AF7AW+hfM6xP9uVSjlnX797mFqm9v5sl5jQJ3D1TMcVDa0sflotd1RlItb3UeNMd0i8hrwmjFGJwxRX1BU3cTTW4q5YXYmI+K0a6Dq26UTUogOC+LVnWUsHKsTEHqC/i5eLyLyYxGpBj4FDolIlYj8hzsvLiLLROSQiBSIyH19rLNIRHaJyH4R+XDgP4LyBA+sO0RIUAD3LB5ndxTl4cKCA/nSlHTe3ldBc3un3XEU/R8a+j7O3kKzjTGJxpgEYC5wgYjcc64NRSQQeBhYDuQCN4lI7lnrxAGPAF8xxkwCrhvMD6HsteP4ad7ce4J/XDiKFL02rXLD1TMcNLd3sf7ASbujKPovBLcCNxljjp15whhTCHzdtexc5gAFxphCV4+j5/niNQy+BrxijDnueu3KgYRX9jPG8LM3D5IcHcrKi0bZHUd5idnZCTjiwvV6xh6iv0IQbIz5whkd13mC/iaPcQAlPR6Xup7raRwQLyIfiMh217UOvkBEVopIvojkV1XpKQpPsm7/SfKLT3PP4nFEhro7Y4nydwEBwooZI9h4pIqqhja74/i9/gpB+yCXAfTWbeTs/mJBwCzgS8BS4P+JyBcOMhtjVhlj8owxecnJenLJU3R1G/73b4cYkxLF9XkZdsdRXubqGQ66DazZrVNO2K2/QjBNROp7uTUAU/rZthTI7PE4Azj7N14KvG2MaXK1PDYA0wbyAyj7vLGnnILKRu5ZPI6gQB08pgZmTEo0UxyxOrjMA5zzr9cYE2iMienlFm2M6e/Q0DZgrIjkiEgIcCNw9tTVfwUWikiQiETgPBF9cLA/jBo+Xd2G3757hAlp0SyfrJeqUINzzUwH+8rqOVShU07YybKPccaYTuBuYB3Of+4vGGP2i8idInKna52DwNvAHuAT4HFjzD6rMqmh8/ruco5WNfG9y8YSEKCDx9TgXDltBEEBwivaKrCVpWf3jDFrcY5C7vncY2c9fgB4wMocamh1dnV/1hpYOklbA2rwkqJCWTQ+mdd2lvHPSycQqB8qbKEHdtWArdldTmF1E99fPE5bA+q8XTMzg5P1OuWEnbQQqAE50xrITY9h6aRUu+MoH3DphBRiwoJ0TIGNtBCoAXltVzlFNc18f/FYnVhODYmw4EC+PG0Eb++roLFNp5ywgxYC5bYOV2tgsiOGJbnaGlBD56szHbR0dPH2vgq7o/glLQTKba/uKOP4qWa+f9k4bQ2oITVzZDxZiRG8skN7D9lBC4FyS0dXNw+9f4SpGbFcNlEvQamGlohwzYwMthTWUFbbYnccv6OFQLnl5e2llJxq0XMDyjJXz3BgDLy2U08aDzctBKpf7Z3dPPReAdMy47hkvLYGlDVGJkYwJzuBV3aUYoxexnI4aSFQ/XppeylltdoaUNa7ZqaDo1VN7CmtszuKX9FCoM6pvbObh98vYHpmHIvG6cyvylrLp6QTEhTAq3p4aFhpIVDn9EJ+CWW1LdyzRHsKKevFhgezJDeVNbvLae/stjuO39BCoPrU1tnFw+8XMHNkHBeNTbI7jvITX53p4FRTOx8e1otQDRctBKpPL2wr4URdq7YG1LBaODaZpKgQXtpe0v/KakhoIVC9au3o4uH3j5KXFc+FY7Q1oIZPcGAAV89w8O7BSqob9TKWw0ELgerVX7aVUFHfyg+0NaBscMPsTDq7jY40HiZaCNQXtHZ08cgHBczJSWD+6ES74yg/NCYlmryseJ7fVqJjCoaBFgL1BX/+5Dgn69u4Z7G2BpR9bpidSWFVE/nFp+2O4vO0EKjPcbYGjjJvlLYGlL2+NDWdqNAgnv9ETxpbTQuB+pxnPi6mqsHZGlDKThEhQVw5bQRr956gvrXD7jg+TQuB+kxLexePfVjIgtGJzB2lrQFlvxtnZ9LS0cXru8vtjuLTtBCozzzzcTHVjW3cs0RbA8ozTM2IZUJaNH/ZpoeHrGRpIRCRZSJySEQKROS+c6w3W0S6RORaK/OovjW3d/LYh0e5cEwSs7MT7I6jFOC8TsGNszPZU1rH/nKdiM4qlhUCEQkEHgaWA7nATSKS28d6vwDWWZVF9e/pLcXUNLVzz5KxdkdR6nNWzHAQEhTAC9oqsIyVLYI5QIExptAY0w48D1zVy3rfAV4GKi3Mos6hqa2T328oZOHYJGZlaWtAeZa4iBCWTUrj1Z1ltHZ02R3HJ1lZCBxAzxJe6nruMyLiAK4GHjvXC4nIShHJF5H8qiqdiGqoPbWlmFNN7XpuQHmsG2dnUt/aydq9J+yO4pOsLAS9jUQ6e4jgr4F7jTHnLPPGmFXGmDxjTF5yss6JP5Qa2zpZteEoF49LZubIeLvjKNWr+aMTGZUcyVNbiu2O4pOsLASlQGaPxxnA2X3A8oDnRaQIuBZ4RERWWJhJneVPm45xurmDH2hrQHkwEeGWeVnsKqllr169bMhZWQi2AWNFJEdEQoAbgTU9VzDG5Bhjso0x2cBLwLeNMa9ZmEn1UNfcwaqNhSyemMq0zDi74yh1Tl+dlUF4cCBPbSmyO4rPsawQGGM6gbtx9gY6CLxgjNkvIneKyJ1WfV/lvsc3FdLQ2qmtAeUVYsKCWTHDwZrd5dQ2t9sdx6dYOo7AGLPWGDPOGDPaGPPfruceM8Z84eSwMeY2Y8xLVuZRf1fT2MbqTcf40tR0ckfE2B1HKbfcOj+Lts5uXszX6amHko4s9lO/31BIS0cX9yzWcQPKe0xMj2F2djzPbC2mu1unpx4qWgj8UGV9K09uLmLFDAdjUqLtjqPUgNwyP5vimma9pvEQ0kLghx754Chd3YbvXaatAeV9lk1KIzUmlD9uOmZ3FJ+hhcDPlNW28NzW41yXl0FWYqTdcZQasJCgAP5hQTabCqo5UF5vdxyfoIXAz/z2nSMA3H2ptgaU97p5ThbhwYHaKhgiWgj8yKGKBl7cXsIt87NwxIXbHUepQYuNCOb6vAzW7C7jZH2r3XG8nhYCP/I/bx0kKjSI71w6xu4oSp23b1yQQ2e30QFmQ0ALgZ/YXFDN+4equOuSMcRFhNgdR6nzlp0UyeW5qTzz8XGa2zvtjuPVtBD4ge5uw8/f+hRHXDj/sCDb7jhKDZk7Fo6irqVDr1VwnrQQ+IHX95Szt6yOH14+jrDgQLvjKDVk8rLiycuKZ9WGQto7u+2O47W0EPi4ts4uHlh3iNz0GFZMd/S/gVJeRES4+9IxlNe18upOnXZisLQQ+LintxRTerqFf71iIgEBvV0iQinvdvG4ZKY4Ynnkg6N0dmmrYDC0EPiw2uZ2HnqvgIvGJXPh2CS74yhliTOtguKaZt7Yo1cwGwwtBD7swfWHaWjt4F+WT7A7ilKWWjIxlfGp0fzu/QKdjG4QtBD4qAPl9TzzcTFfn5fFxHSdZlr5toAA4a5Lx1BQ2chb+yrsjuN1tBD4IGMMP16zn9jwYL3ojPIbX5qSzpiUKB5cf0jPFQyQFgIf9PqeE3xSdIofLZ2gg8eU3wgMEP7p8vEcrWrilR1ldsfxKloIfExTWyc/e/Mgkx0x3DA70+44Sg2rpZOc19/+1TuHae3osjuO19BC4GMeXH+YivpW/usrkwjU7qLKz4gI9y4bz4m6Vp7eUmx3HK+hhcCH7Cmt5U8fHePmuSOZlZVgdxylbLFgdBILxybx8AcF1Ld22B3HK2gh8BEdXd3c9/JekqJCuVe7iyo/d++yCdQ2d/DoB0ftjuIVLC0EIrJMRA6JSIGI3NfL8ptFZI/rtllEplmZx5et3nSMAyfquf+qScSEBdsdRylbTXbEcs0MB3/ceIyi6ia743g8ywqBiAQCDwPLgVzgJhHJPWu1Y8DFxpipwE+AVVbl8WXFNU386p3DLMlNZemkNLvjKOUR7ls+gZCgAO5/44DdUTyelS2COUCBMabQGNMOPA9c1XMFY8xmY8xp18OPgQwL8/ikrm7DD1/YTXBgAPdfNQkRPUGsFEBKTBjfvWwM731ayXufnrQ7jkezshA4gJ6ThJe6nuvL7cBbFubxSas2FJJffJr7r5pEeqxeflKpnm5bkMOo5Ejuf/0AbZ3anbQvVhaC3j6a9joJiIhcgrMQ3NvH8pUiki8i+VVVVUMY0bsdPFHPg+sPsXxymk4xrVQvQoIC+PGVkyiqaWbVh4V2x/FYVhaCUqDniKYMoPzslURkKvA4cJUxpqa3FzLGrDLG5Blj8pKTky0J623aOru45y+7iA0P4b+vnqKHhJTqw0XjkvnSlHQeeq+Awycb7I7jkawsBNuAsSKSIyIhwI3Amp4riMhI4BXgFmPMYQuz+Jyfr/2UTysa+MVXp5AQqdNIKHUu/3XVJCJDA/nRS3t0HqJeWFYIjDGdwN3AOuAg8IIxZr+I3Ckid7pW+w8gEXhERHaJSL5VeXzJ2r0neGJzEd+8IIfLJqbaHUcpj5cUFcr9V01md0ktj286ZnccjxNk5YsbY9YCa8967rEe9+8A7rAyg68pqm7in1/aw/TMOO7TgWNKue3LU9N5Y085D64/zOKJqYxJibI7ksfQkcVepLWji28/u4OgQOHhm2cSEqS/PqXcJSL8ZMVkIkIC+f5fdmovoh70P4mXMMZw38t7OHCinl9dPx1HnHYVVWqgUqLD+OVXp7KvrJ6fvXnQ7jgeQwuBl3jovQJe21XOj5aO55IJKXbHUcprXT4pjTsuzOHJLcW8qdc4BrQQeIXXdzuPa14z08G3F422O45SXu/e5ROYMTKOe1/eo3MRoYXA420vPsUPX9zNnOwEfn6NjhdQaigEBwbw0E0zCAwQvvX0dr+frloLgQfbV1bHbX/axojYMB67ZRahQYF2R1LKZ2TER/DIzTM5WtXIXc/uoMOPxxdoIfBQBZUN3Lr6E2LCgnn2H+fpoDGlLHDBmCR+ds0UNh6p5t9f3Ycxvc6C4/MsHUegBqe4pombH99KYIDwzB1ztYeQUha6Pi+T4zXN/O79Ahzx4Xz3srF2Rxp2Wgg8zMET9dy6+hM6u7p5fuV8cpIi7Y6klM/74eXjKKtt4cH1hwkKFL69aIzdkYaVFgIPsq3oFN98YhtRoUE8d8d8xqZG2x1JKb8gIjxw7VS6ug2/fPsQxsBdl/hPMdBC4CH+tr+C7z6/kxFx4Tx9ux4OUmq4BQUG8OD10xCBB9Ydoqvb8J1Lx/hFTz0tBDbr7jb85t0j/ObdI0zLiGX1bbNJjAq1O5ZSfslZDKYTKMKD6w9TerqZn66Y4vPTuWghsFF9awc/+Msu3jlYybWzMvjpismEBWsXUaXsFBgg/O9108iID+e37xVQcqqFR78+k7gI3+2559tlzoN9XFjD8l9v5INDVdx/1SQeuHaqFgGlPERAgPCDy8fzqxumsb34NFc9/BG7SmrtjmUZLQTDrLWji5+8cYCb/vAxwYHCX741n1vnZ/vFcUilvM3VMzL488q5dHYZrn10Mw+/X0BXt++NNdBCMEyMMfxtfwVLf72BP246xtfnZrH2ewuZlRVvdzSl1DnMykpg7fcWsnxKOg+sO8SNq7ZwqMK3Lnmp5wiGwacV9fz3mwfZeKSasSlRPHvHXC4Yk2R3LKWUm2LDg/ntjdO5ZHwy979xgCt+u5Fb52fx/cXjiA0PtjveedNCYKF9ZXU89N4R1u0/SUxYED++Mpeb52URHKgNMaW8jYhwzcwMLhmfwv+tP8QTm4v4665y7liYw63zs4kK9d5/p96b3EN1dnXzzsFKnt1azMYj1USHBfHdy8byzQuyfbrXgVL+Ij4yhJ+umMKNs0fywLpD/PLtQ6zaUMhtC7L52pyRpMSE2R1xwLQQDAFjDAdO1PPmnhO8vKOUk/VtpMWE8aOl47llfhYxYd7fdFRKfd5kRyxPfnMOu0tqeei9An79zhEeeq+AxRNTuHH2SC4cm+Q1rX8tBIPU2tFFftFpNh6pYt3+CopqmgkMEC4am8RPV2RxyfhkgrxkJ1BKDd60zDge/4c8jlU38fwnx3lxe+lnh4MX56aybFIa80cnEu3BHwi1ELjBGMPJ+jZ2l9ayq6SWncdPs+N4Le2d3QQHCvNGJfKti0ezdFKaThetlJ/KSYrkX66YyA8uH8eHh6p4e38F7xw4ySs7yggMEKY4Ypk3KpFpGbHkjohhZEKEx3Qbt7QQiMgy4DdAIPC4MeZ/zlouruVXAM3AbcaYHVZm6ktXt6G6sY3y2hYq6lopPtVMQWUjBZWNHK1qpKG1E4CgAGFCejS3zMviwjFJzMlJINKLTxIppYZWaFAgl09K4/JJaXR0dbOt6BRbjtaw+WgNj28spNM1DiE6NIiJI2IYnxrNyIQIMhPCyUyIIDMhgujQoGEtEpb9BxORQOBhYAlQCmwTkTXGmAM9VlsOjHXd5gKPur4OuaNVjbxz4CS1LR3UNndQ19JObbPz/unmdiob2r4wUCQpKpQxKZGsmO5gTEoUkx0xTBoRqyOAlVJuCQ4MYMHoJBaMTuKHOA8pHz7ZwP7yevaX17G/vJ6/7iqj3vVB84zQoAASI0NIiAohITKUhIhgEiJDuWhcEovGpwx5Tis/ys4BCowxhQAi8jxwFdCzEFwFPGWclwX6WETiRCTdGHNiqMMcOdnAz9/6lOBAITY8hLiIYOLCgxkRF8bE9BjSYkNJiw0nPSaM9LgwMuIiiI3w3GN6SinvExYcyNSMOKZmxH3u+brmDkpON1NyqpmS081UN7ZT09jOqaY2TjW1U1jVyKmmdiJDA72uEDiAkh6PS/nip/3e1nEAnysEIrISWOl62CgihwaQIwmoHsD6w0mzDY6nZvPUXGBxtpvPb3O/fd8G6p9cNwaXK6uvBVYWgt4OcJ09SYc762CMWQWsGlQIkXxjTN5gtrWaZhscT83mqblAsw2Wp2Yb6lxW9m8sBTJ7PM4AygexjlJKKQtZWQi2AWNFJEdEQoAbgTVnrbMGuFWc5gF1VpwfUEop1TfLDg0ZYzpF5G5gHc7uo6uNMftF5E7X8seAtTi7jhbg7D76DQuiDOqQ0jDRbIPjqdk8NRdotsHy1GxDmkucHXaUUkr5K50DQSml/JwWAqWU8nM+UQhEJEFE1ovIEdfXXi/7JSJFIrJXRHaJSP5At7cqm4hkisj7InJQRPaLyPd6LPuxiJS5Mu8SkSvOM88yETkkIgUicl8vy0VEfutavkdEZrq77flyI9vNrkx7RGSziEzrsazX3+0wZlskInU9fk//4e62w5DtRz1y7RORLhFJcC2z7H0TkdUiUiki+/pYbsu+5kYuO/ez/rJZs58ZY7z+BvwSuM91/z7gF32sVwQkDXZ7q7IB6cBM1/1o4DCQ63r8Y+CfhihLIHAUGAWEALvPfJ8e61wBvIVzjMc8YKu72w5DtgVAvOv+8jPZzvW7HcZsi4A3BrOt1dnOWv9K4L1het8uAmYC+/pYbte+1l8uW/YzN7NZsp/5RIsA51QVT7ruPwmsGObtz+u1jTEnjGuyPWNMA3AQ5wjrofbZtB/GmHbgzLQfZ+d9yjh9DMSJSLqb21qazRiz2Rhz2vXwY5zjTobD+fzstr9vZ7kJ+PMQfv8+GWM2AKfOsYot+1p/uWzcz9x5z/pyXu+ZrxSCVOMaf+D62tdkHAb4m4hsF+e0FQPd3spsAIhINjAD2Nrj6btdzdTV53nYqq8pPdxZx51tz8dAX/92nJ8mz+jrdzuc2eaLyG4ReUtEJg1wW6uzISIRwDLg5R5PW/m+9ceufW0ghnM/c9eQ72deM3+yiLwDpPWy6N8G8DIXGGPKRSQFWC8in7oqsCdkQ0SicP6Rft8YU+96+lHgJzh3wJ8A/wd8c7BRe3nO3Wk/3JoO5Dy4/foicgnOP9ALezxtye92ANl2AFnGmEZxnsd5Deesuh7zvuE8LPSRMabnJ04r37f+2LWvucWG/cwdluxnXlMIjDGL+1omIifFNWupq2lZ2cdrlLu+VorIqzibUxsAt7a3MpuIBOMsAs8aY17p8done6zzB+CNgWQ7y/lM+xHixrbnw63pRkRkKvA4sNwYU3Pm+XP8boclW4/CjTFmrYg8IiJJ7mxrdbYebuSsw0IWv2/9sWtf65dN+1m/LNvPrDrpMZw34AE+f0L2l72sEwlE97i/GVjm7vYWZxPgKeDXvSxL73H/HuD588gSBBQCOfz9hNKks9b5Ep8/gfeJu9ue5/vkTraROEehL3D3dzuM2dL4+wDNOcBx13to+/vmWi8W57HnyOF631yvm03fJz5t2dfcyGXLfuZmNkv2syH9Aey6AYnAu8AR19cE1/MjgLWu+6Ncb85uYD/wb/1tP4zZLsTZjNsD7HLdrnAtexrY61q2hh6FYZB5rsDZK+nomfcAuBO403VfcF5Q6Kjr++ada9sh/j32l+1x4HSP9yi/v9/tMGa72/W9d+M8wbjgXNsOZzbX49s460OE1e8bztbHCaAD5yfW2z1hX3Mjl537WX/ZLNnPdIoJpZTyc77Sa0gppdQgaSFQSik/p4VAKaX8nBYCpZTyc1oIlFLKz2khUEopP6eFQCml/Nz/B7mtgcZqmHm7AAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.distplot(pd.DataFrame(arr_ex.reshape(9,1)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "65074c1c",
   "metadata": {},
   "source": [
    "**Randint**\n",
    "\n",
    "*np.random.randint(start,end(excluding),number of int)*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "id": "db3db2b8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([7, 5, 7, 4, 0, 6, 2, 2, 5])"
      ]
     },
     "execution_count": 113,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"F:\\DS\\anaconda3\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    }
   ],
   "source": [
    "np.random.randint(0,8,9)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3863fb7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
